apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yml
- deployment.yml
- service.yml
- ingress.yml

namespace: configuracao
images:
- name: 247761945410.dkr.ecr.sa-east-1.amazonaws.com/justto/configurations-bff
  newName: 247761945410.dkr.ecr.sa-east-1.amazonaws.com/justto/configurations-bff
  newTag: daa4760f35ce21f721879cf4af0f33b14803b23f
